In [ ]:
from sentiment_classifier.utils.utils import get_root_dir
from sentiment_classifier.data.retrieval import read_csv

from sentiment_classifier.data.retrieval import get_train_test_data

In [ ]:
root = get_root_dir()
data_path = root / "data" /"all-data.csv"

In [ ]:
df = read_csv(data_path, encoding='latin-1', header=None, names = ["sentiment", "text"])

In [ ]:
train, test = get_train_test_data(df, test_size=0.2)

# Preparing the model

In [ ]:
import spacy
nlp=spacy.load("en_core_web_trf")

In [ ]:
#Creating tuples
train['tuples'] = train.apply(lambda row: (row['text'],row['sentiment']), axis=1)
train_tuple = train['tuples'].tolist()

test['tuples'] = test.apply(lambda row: (row['text'],row['sentiment']), axis=1)
test_tuple = test['tuples'].tolist()

In [ ]:
def get_list_of_tuples(df):
    """
    Get list of tuples from a dataframe.

    :param df: dataframe
    :return: list of tuples
    """
    df['tuples'] = df.apply(lambda row: (row['text'],row['sentiment']), axis=1)
    return df['tuples'].tolist()

In [ ]:
train_tuple

In [ ]:
for doc, label in nlp.pipe(train_tuple, as_tuples=True):
    print(doc, label)

In [ ]:
help(doc)

In [ ]:
def create_spacy_documents(data):
  """
  This function takes in a list of tuples and returns a list of spacy documents.
  """
  text = []
  for doc, label in nlp.pipe(data, as_tuples = True):
    if (label=='positive'):
      doc.cats['positive'] = 1
      doc.cats['negative'] = 0
      doc.cats['neutral']  = 0
    elif (label=='negative'):
      doc.cats['positive'] = 0
      doc.cats['negative'] = 1
      doc.cats['neutral']  = 0
    else:
      doc.cats['positive'] = 0
      doc.cats['negative'] = 0
      doc.cats['neutral']  = 1
      text.append(doc)
  return(text)

In [ ]:
type(nlp)

In [ ]:
isinstance(type(nlp), spacy.lang.en.English)

In [ ]:
help(nlp)

In [3]:
from sentiment_classifier.utils.utils import load_spacy_model
from sentiment_classifier.utils.utils import get_root_dir
from sentiment_classifier.data.retrieval import get_train_test_data
from sentiment_classifier.data.retrieval import read_csv
from sentiment_classifier.data.training_dataset import get_list_of_tuples
from sentiment_classifier.data.training_dataset import create_spacy_documents
import mlflow 
import spacy

In [5]:
nlp = load_spacy_model(model_path="models/model-best")

c:\Users\manue\Documents\NLP_usecases\sentiment_classifier\.venv\Lib\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
c:\Users\manue\Documents\NLP_usecases\sentiment_classifier\.venv\Lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(

In [6]:
example = "According to Gran , the company has no plans to move all production to Russia , although that is where the company is growing"
doc = nlp(example)

In [7]:
doc.cats

{'positive': 0.45736005902290344,
 'negative': 0.043489351868629456,
 'neutral': 0.4991506040096283}

In [6]:
with mlflow.start_run(run_name = "logging_model") as run:
    mlflow.spacy.log_model(spacy_model=nlp, artifact_path="sentiment_classifier")

In [179]:
loaded_model = mlflow.pyfunc.load_model(model_uri=f"runs:/{run.info.run_id}/sentiment_classifier")
spacy_model = mlflow.spacy.load_model(model_uri=f"runs:/{run.info.run_id}/sentiment_classifier")

In [13]:
nlp = spacy.blank("en")

In [75]:

root = get_root_dir() 
data_path = root / "data" /"all-data.csv" 
df = read_csv(data_path, encoding='latin-1', header=None, names = ["sentiment", "text"])

train, test = get_train_test_data(df)
train_data = get_list_of_tuples(train)
test_data = get_list_of_tuples(test)

test_docs = create_spacy_documents(nlp = nlp, data = test_data)

In [76]:
test_docs[0].cats

{'positive': 0, 'negative': 0, 'neutral': 1}

In [77]:
test["text"]

3207    The company was supposed to deliver machinery ...
1684    UNC Charlotte would also deploy SSH Tectia Con...
1044    In 2009 , Lee & Man had a combined annual prod...
4145    `` That 's a very high figure on the European ...
1538    In Finland , the corresponding service is Alma...
                              ...
3691    News Corp. 's MySpace.com Web site will displa...
1507    Both Mr Walden and Mr Ignatius will be respons...
1126    `` Every partner will be allowed to buy a quan...
180     Diluted earnings per share ( EPS ) rose to EUR...
1215    Entire paper mills may be set up , especially ...
Name: text, Length: 970, dtype: object

In [ ]:
from mlflow.metrics import make_metric
from mlflow.metrics import MetricValue


def eval_fn(predictions, targets, context):
    values = predictions.iloc[0].values[0]
    
    scores = (predictions == targets) + context
    return MetricValue(
        scores=list(scores),
        aggregate_results={"mean": np.mean(scores), "sum": np.sum(scores)},
    )


mymetric = make_metric(eval_fn=eval_fn, greater_is_better=False, name="mymetric")

In [84]:
predictions = loaded_model.predict(test[["text"]])

In [89]:
predictions.iloc[0].values[0]

{'positive': 0.21659491956233978,
 'negative': 0.03428983315825462,
 'neutral': 0.7491152882575989}

In [134]:
from mlflow.metrics import EvaluationMetric
from mlflow.metrics import MetricValue
import pandas as pd
import operator
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import f1_score

In [152]:
def eval_fn(predictions: pd.Series, targets: pd.Series)->float:
    """
    """ 
    df = pd.DataFrame(predictions, columns=["predictions"])
    df["prediction"] = df["predictions"].apply( lambda x : max(x.items(), key = operator.itemgetter(1))[0])
    df["target"] = targets
    accuracy_score = balanced_accuracy_score(df["target"], df["prediction"])
    return accuracy_score

In [161]:
eval_fn(predictions, test["sentiment"])

0.7136766252995294

In [153]:
custom_acc = EvaluationMetric(eval_fn=eval_fn, name="custom_acc", greater_is_better=True)

In [175]:
loaded_model.predict(test[["text"]])

                                            predictions
3207  {'positive': 0.21659491956233978, 'negative': ...
1684  {'positive': 0.34155046939849854, 'negative': ...
1044  {'positive': 0.8569769263267517, 'negative': 0...
4145  {'positive': 0.255377858877182, 'negative': 0....
1538  {'positive': 0.24798519909381866, 'negative': ...
...                                                 ...
3691  {'positive': 0.2780744135379791, 'negative': 0...
1507  {'positive': 0.17686673998832703, 'negative': ...
1126  {'positive': 0.16717375814914703, 'negative': ...
180   {'positive': 0.9693070650100708, 'negative': 0...
1215  {'positive': 0.19200772047042847, 'negative': ...

[970 rows x 1 columns]

In [176]:
labels = {"positive": 2, "negative": 0, "neutral": 1}
test["label"] = test["sentiment"].apply(lambda x: labels[x])

In [177]:
model_uri = f"runs:/{run.info.run_id}/sentiment_classifier"
result = mlflow.evaluate(
    model = model_uri,
    data=test[["text", "sentiment"]],
    model_type=None,
    targets = "sentiment",
    evaluators = None,
    extra_metrics = [custom_acc],
)

# result = mlflow.evaluate(
#     model=loaded_model,
#     data = eval_data,
#     model_type=None, # to avoid internal metrics calculation
#     targets="target",
#     extra_metrics=[custom_acc],
# )

c:\Users\manue\Documents\NLP_usecases\sentiment_classifier\.venv\Lib\site-packages\mlflow\data\digest_utils.py:26: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  string_columns = trimmed_df.columns[(df.applymap(type) == str).all(0)]
c:\Users\manue\Documents\NLP_usecases\sentiment_classifier\.venv\Lib\site-packages\mlflow\models\evaluation\base.py:521: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  data = data.applymap(_hash_array_like_element_as_bytes)
c:\Users\manue\Documents\NLP_usecases\sentiment_classifier\.venv\Lib\site-packages\mlflow\models\evaluation\base.py:521: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  data = data.applymap(_hash_array_like_element_as_bytes)
2024/04/14 10:06:31 INFO mlflow.models.evaluation.base: Evaluating the model with the default evaluator.
2024/04/14 10:06:31 INFO mlflow.models.evaluation.default_evaluator: Computing model predictions.
2024/04/14 10:06:46 INFO mlflow.models.evaluation.default_evaluator: Testing metrics on first row...

MlflowException: Metric 'custom_acc': Error:
ValueError("Classification metrics can't handle a mix of binary and unknown targets")
Traceback (most recent call last):
  File "c:\Users\manue\Documents\NLP_usecases\sentiment_classifier\.venv\Lib\site-packages\mlflow\models\evaluation\default_evaluator.py", line 1615, in _test_first_row
    metric_value = _evaluate_metric(metric_tuple, eval_fn_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\manue\Documents\NLP_usecases\sentiment_classifier\.venv\Lib\site-packages\mlflow\models\evaluation\default_evaluator.py", line 598, in _evaluate_metric
    metric = metric_tuple.function(*eval_fn_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manue\AppData\Local\Temp\ipykernel_12728\165372255.py", line 7, in eval_fn
    accuracy_score = balanced_accuracy_score(df["target"], df["prediction"])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\manue\Documents\NLP_usecases\sentiment_classifier\.venv\Lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\manue\Documents\NLP_usecases\sentiment_classifier\.venv\Lib\site-packages\sklearn\metrics\_classification.py", line 2454, in balanced_accuracy_score
    C = confusion_matrix(y_true, y_pred, sample_weight=sample_weight)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\manue\Documents\NLP_usecases\sentiment_classifier\.venv\Lib\site-packages\sklearn\utils\_param_validation.py", line 186, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\manue\Documents\NLP_usecases\sentiment_classifier\.venv\Lib\site-packages\sklearn\metrics\_classification.py", line 319, in confusion_matrix
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\manue\Documents\NLP_usecases\sentiment_classifier\.venv\Lib\site-packages\sklearn\metrics\_classification.py", line 94, in _check_targets
    raise ValueError(
ValueError: Classification metrics can't handle a mix of binary and unknown targets

In [170]:
result

NameError: name 'result' is not defined

In [182]:
test_docs

[The company was supposed to deliver machinery to a veneer mill in the Tomsk region , in Russia .,
 UNC Charlotte would also deploy SSH Tectia Connector to enable secure application connectivity .,
 In 2009 , Lee & Man had a combined annual production capacity of close to 4.5 million tonnes of paper and 300,000 tonnes of pulp .,
 `` That 's a very high figure on the European scale , '' Noop said , recalling however that this also includes beer bought by Finnish tourists .,
 In Finland , the corresponding service is Alma Media 's Etuovi.com , Finland 's most popular and best known nationwide online service for home and property sales .,
 Construction is scheduled to start in April-June 2007 and to be completed in early 2008 .,
 Finnish-owned contract manufacturer of electronics Elcoteq Hungary Kft has announced plans to recruit more than 650 new staffers to fulfill new orders in P+_cs , where the company has two plants .,
 The gross area of the Innova 2 project will be about 10,000 sq m ( 107,600 sq ft ) .,
 Finnish home decoration and arts and crafts retailer Tiimari Plc ( OMX Helsinki : TII1V ) reported on Monday ( 18 August ) an operating loss of EUR3 .3 m on net sales of EUR33 .9 m for the period January-June 2008 .,
 Deliveries will start in the second half of 2007 and the start-up of the mill is scheduled for 2008 .,
 Steek , which was set up in 2002 , is based in Bordeaux , southwestern France .,
 Outotec said it won new orders worth 492.9 mln eur during the quarter , compared with 240.4 mln eur a year earlier .,
 The store is located in Poznan in a shopping center named Pestka , the company added .,
 The value of the order is USD 2.2 mn .,
 The company expects meat purchases to remain at about 8mn kilos in 2011 .,
 Finnish house manufacturers are targeting the strongly growing one-family house market in Russia .,
 The deal was worth about EUR 1.2 mn .,
 Any investment or investment activity to which this communication relates is only available to relevant persons and will be engaged in only with relevant persons .,
 Following the increase the company+EUR TM s capital totals 5.5 mln Romanian lei $ 1.98 mln-1 .56 mln euro .,
 Since the association 's data do not cover sales figures from about 100 small local breweries and sales of imported beer products , the actual market shares of its members are smaller than those given in the report .,
 According to the Latvian business register , Uponor Latvia closed in red with LVL 99,000 EUR 139,538.17 USD 194,556.48 on turnover of LVL 2.346 mn for 2009 .,
 The issue came up in connection with discussion with local municipalities concerning the sale of water to industrial facilities .,
 Operating profit rose to EUR 13.1 mn from EUR 8.7 mn in the corresponding period in 2007 representing 7.7 % of net sales .,
 Its annual capacity is some 10,000 MW .,
 The Finnish company is building a 800,000 mt-year biodiesel plant in Singapore .,
 The long-standing partnership and commitment enable both parties to develop their respective operations , and ESL Shipping will also have the opportunity to update its fleet and improve its efficiency .,
 Aldata Solution , a global company engaged in supplier to consumer business process optimization , has announced the details of its Dollars for Dinosaurs program .,
 The reasons behind the estimate include the rise in 2008 rent levels and several fully-leased office and retail properties , which were completed and added to the company 's investment property portfolio .,
 Finnish beverage company Olvi is introducing a new long drink Olvi Kultalonkero ( `` golden long drink '' ) in the market in Finland in the spring of 2009 .,
 The current reference grade instruments are challenging to operate due to their high price and complexity for routine use .,
 Rental of building equipment accounted for 88 percent of the operating income .,
 After piloting , the instrument will be further developed according to the experiences gained .,
 The goal will be achieved via organic growth possibly supplemented by acquisitions .,
 Operating profit fell from EUR 7.9 mn in the second quarter of 2005 to EUR 5.1 mn in the second quarter of 2006 .,
 The 3C Expo is a signature show in Dongguan , which is supported by the Dongguan Municipal Government every year , featuring computer accessories , software , communication and network products .,
 Ruukki Romania , the local arm of Finnish metal producer Ruukki , increased its capital by 900,000 euro ( $ 1.14 mln ) through cash contribution , it was reported on September 19 , 2006 .,
 Nokia s U.S. shares were 3.3 percent lower at $ 12.73 by 1750 GMT .,
 Finnish component supplier Componenta Corporation ( OMX Helsinki : CTH1V ) reported on Tuesday ( 15 July ) an operating profit of EUR46 .2 m on net sales of EUR386 .0 m for the financial period January-June 2008 .,
 Elite Residence Tower , a new development by Tameer , is located at the heart of Dubai Marina .,
 The lay-offs will affect 240 people out of the total 320 Okmetic employees in Finland .,
 `` With this agreement , we can continue our good cooperationand at the same time release capital that has been tied up in ourmachinery operation .,
 Travel expenses would be reimbursed in accordance with the travel policy of the company .,
 Ahlstrom Corporation Anne Pirila Director , Financial communications Distribution : Helsinki Stock Exchange Main media Ahlstrom in brief Ahlstrom is a leader in the development , manufacture and marketing of high performance fiber-based materials .,
 In 2007 , almost two thirds of Orion 's net sales came from these drugs .,
 Net income from life insurance doubled to EUR 6.8 mn from EUR 3.2 mn , and net income from non-life insurance rose to EUR 5.2 mn from EUR 1.5 mn in the corresponding period in 2009 .,
 According to Aktia Asset Management , Finnish analysts ' forecasts for 2009 are still too high .,
 Ramirent is the leading construction machinery rental company in Finland with annual sales of EUR 134 million in 2009 and operating nationwide through 83 outlets and 612 employees .,
 In 2006 , TeliaSonera net sales were SEK 91 bn , EBITDA was SEK 32.266 bn , net income was SEK 19.28 bn .,
 The chain posted sales of 298 million euros for full 2005 , a rise of 19.5 percent , year-on-year .,
 Scanfil expects net sales in 2008 to remain at the 2007 level .,
 The profit after taxes was EUR 57.7 11.1 million .,
 The company also appointed Leif Rosen head of the Special Plate unit which includes the quarto plate units in Degerfors , Sweden , and New Castle , USA , the unit in Willich , Germany , as well as Pressplate and Prefab in Avesta and Plate Service Centre Nordic in Degerfors .,
 `` UPM 's deliveries increased during the third quarter by 4 percent , and the efficiency of operations improved , '' Chief Executive Jussi Pesonen said .,
 Operating profit for the 12-month period decreased from EUR2 .9 m while turnover increased from EUR24 .5 m , as compared to the financial year 2004 .,
 cents The profile contains business operations , the company history , major products and services , prospects , key competitors , structure and key employees , locations and subsidiaries .,
 Profit after taxes for the period was up to EUR0 .9 m , from EUR0 .01 m last year .,
 The newly-completed Allure of the Seas and its identical sister ship , Oasis of the Seas , which was completed last year are the world 's largest cruise ships .,
 The number of class A shares remains unchanged at 9,526,089 shares .,
 Under the rental agreement , Stockmann was committed to invest in the building of a bridge over the Gogol Street or build an underground tunnel for crossing the street by 2004 .,
 Honkarakenne 's customer in this project is one of the biggest real estate companies in Kazakhstan , according to the company .,
 This new deal has strengthened the partnership from Telemig Celular and Tecnomen , which it has started since the beginning of Telemig 's prepaid operations .,
 Turun kaupunkin , Finland based company has awarded contract to Lemminkainen Talotekniikka Oy for electrical installation work .,
 Based on the first quarter result , existing order backlog and new order prospects , the company expects that full-year sales will contract by 25 % from 2008 , the gross margin will stay at a healthy level , and the operating profit margin will be lower than in 2008 due to lower sales volume .,
 An audio webcast will be available live and archived on Cerner 's Web site at www.cerner.com .,
 Earnings per share ( EPS ) for the first quarter 2007 amounted to EUR0 .07 , up from EUR0 .04 .,
 Under the transaction agreement , Metsaliitto will purchase 24.7 % of Metsa-Botnia 's shares from UPM and 3 % from M-real .,
 SKF 6 April 2010 - Alandsbanken has given a `` buy '' recommendation on Swedish industrial company SKF AB ( STO : SKF B ) with a share price target of SEK150 .,
 Return on investment was 16.6 % compared to 15.8 % in 2004 .,
 Citigroup , Inc NYSE : C , Deutsche Bank NYSE : DB and Pohjola Bank are lead managers for the sale .,
 - The Group - s profit before taxes was EUR 0,2 7,8 million .,
 The company has a wide selection of metal products and services .,
 Both operating profit and turnover for the three-month period increased , respectively from EUR0 .9 m and EUR8 .3 m , as compared to the corresponding period in 2005 .,
 Elcoteq 's revenues in 2007 were approximately EUR 120 million .,
 Previously , Vaahto Pulp has supplied headboxes with rectifier roll and dilution control technology for Stora Enso 's mill in Imatra , eastern Finland .,
 `` This vessel order will help Aspo secure the long-term competitiveness of its fleet , both in terms of technology and pricing .,
 Aspocomp intends to set up a plant to manufacture printed circuit boards with an investment of Rs310 crore .,
 The Finnish company sold its UK operation - consisting of 50 staff in offices in London , Birmingham and Manchester - as part of a deal with Hampden in July 2001 for its European-wide property and casualty arm Sampo Industrial .,
 Aspo serves demanding business-to-business customers .,
 Tikkurila , a division of Kemira group , controls about 23 % of the Russian market in its field and owns St. Petersburg paint producer TEX. .,
 Viking Line 's cargo revenue increased by 5.4 % to EUR 21.46 mn , and cargo volume increased by 2.4 % to 70,116 cargo units .,
 The Internal Revenue Service sees about 20 percent of all taxpayers wait until the last two weeks to file , with about 40 million returns filed in April .,
 `` Adjustment to the fall in price level , in contrast , has been less effective .,
 Digia said its consolidated net sales for January-June 2010 were EUR67 .8 m , up 9.7 % on the same period in 2009 ( EUR61 .9 m ) .,
 Finnish shipping company Finnlines ' pretax loss totalled EUR 6.5 mn in the third quarter of 2009 , compared to a profit of EUR 0.3 mn in the third quarter of 2008 .,
 Finnish security and privacy software solutions developer Stonesoft Oyj said on January 7 , 2008 that the preliminary sales of its StoneGate products grew by 59 pct year-on-year to 3.6 mln euro ( $ 5.3 mln ) for the fourth quarter of 2007 .,
 Finnish Cargotec 's Kalmar has received a significant order from the US Department of Defense .,
 Most of the new substations support EDGE technology , which enables faster data traffic .,
 ( ADP News ) - Feb 11 , 2009 - Finnish management software solutions provider Ixonos Oyj ( HEL : XNS1V ) said today its net profit rose to EUR 3.5 million ( USD 4.5 m ) for 2008 from EUR 3.1 million for 2007 .,
 ` It is a testament to the quality of our LTE solution and our commitment to the Japanese market ' , he added .,
 Nokia - the world 's largest mobile phone manufacturer - and China Postel - China 's largest mobile phone distributor - have a long-standing partnership that continues to grow stronger over time .,
 Finnish forest machinery manufacturer Ponsse 's net sales grew to EUR 51.3 mn in the first quarter of 2010 from EUR 37.5 mn in the corresponding period in 2009 .,
 The credit covers approximately 70 % of the ship 's price .,
 The employment contracts of 14 of the employees will end in March 2009 as a result of the company 's previous employer-employee talks .,
 Finnish Neste Oil that was previously on the list , has fallen off the list completely .,
 PGE Belchatow runs the 4.44 GW Belchatow coal-fired power plant , and Fortum has intentions to start a CCS demonstration project jointly with Teollisuuden Voima Oyj ( TVO ) - another Finnish utility - at the their jointly owned 565MW Meri-Pori coal-fired facility .,
 The company has exported into about twenty European countries as well as to Africa .,
 A total six of the polled analysts rated M-real -- two gave `` buy '' - `` accumulate '' , three gave `` hold '' and only one gave `` sell '' .,
 M-real , which is part of Finnish paper maker Metsaliitto Group , is due to release its second-quarter report at around 12:00 EET on 5 August 2010 .,
 ( ADP News ) - Nov 28 , 2008 - Finnish power-supply solutions provider Efore Oyj ( OMX : EFO1V ) announced today the launch of OPUS DC , the latest power system in its OPUS product line .,
 A total of 1,800,000 stock options were issued in the 2003 stock option scheme .,
 Following the transaction , Tulikivi restructured its operations into the Soapstone Fireplaces Business , Natural Stone Product Business and Ceramic Products Business units .,
 The company 's share is listed in the Mid Cap segment of the NASDAQ OMX Helsinki .,
 The sale will be finalized in September or October , the company said .,
 The value of the orders is about EUR 70mn .,
 The train is expected to cross the Russian territory in 9 days , reaching the Vostochny port .,
 Altogether 150 subjects with mildly elevated cholesterol levels participated in the four-month long intervention .,
 In 2008 Stockmann earned 3.398 million lats in profit on 48.012 million lats in turnover .,
 Finnish automation solutions developer Cencorp Corporation ( OMX Helsinki : CNC1V ) said on Friday ( 27 June ) that it has completed employee negotiations regarding a reorganisation of its operations .,
 Operating profit for the six-month period decreased from EUR111 .9 m , while sales increased from EUR1 ,275 m , as compared to the corresponding period in 2006 .,
 Belarus OAO Lidskoe Pivo brewery , based in the Grodno Region , reported a 1.1 % decrease in output to 1.045 million decaliters in January-March 2010 , a representative in the administration of the company told .,
 The plant will go on stream in November 2008 and its estimated daily production will be 120,000 litres of bioethanol .,
 `` The acquisition of Elektros Pavara completes KONE 's market expansion strategy in the Baltic Countries .,
 Finnish plumbing and heating systems supplier Uponor 's net sales in continuing business operations decreased to EUR 249.1 mn in July-September 2008 , compared to EUR 262.1 mn in the third quarter of 2007 .,
 Elcoteq SE Stock Exchange Announcement February 4 , 2009 at 10.00 am ( EET ) Elcoteq will publish its financial statements bulletin 2008 on Wednesday , February 11 , at 9.00 am ( EET ) .,
 TELECOMWORLDWIRE-7 April 2006-TJ Group Plc sells stake in Morning Digital Design Oy Finnish IT company TJ Group Plc said on Friday 7 April that it had signed an agreement on selling its shares of Morning Digital Design Oy to Edita Oyj .,
 Nokian Capacitors ' equipment will be used to raise the capacity and reliability of the Indian grid .,
 HUHTAMAKI OYJ STOCK EXCHANGE RELEASE 16.12.2008 AT 09:30 Huhtamaki Oyj has resolved to clarify the Group structure by separating the Foodservice and Consumer Goods businesses in its production unit in Hameenlinna , Finland by transferring the businesses into its wholly owned subsidiaries .,
 The German company has also signed a code share agreement with another Oneworld member -- American Airlines Inc , part of US-based AMR Corp ( NYSE : AMR ) .,
 Finnish fibers and plastic products maker Suominen Corporation said its net loss narrowed to 1.6 mln euro $ 2.0 mln in the first nine months of 2006 from 2.16 mln euro $ 2.7 mln in the same period of 2005 .,
 Olvi 's target is to strengthen its market share in soft drinks , mineral waters , ciders , long drinks , and energy drinks .,
 `` We have tailored our solutions to meet Solel 's technical requirements , and the result is both cost-effective manufacturing and highest-quality reflectors . '',
 Reporting in accordance with the merged business operations will start as of January 1 , 2011 .,
 The RME from Telcontar enables the handset to calculate the best route and includes support for user-defined routes , feature navigability and multi-modal routing such as via foot and ferry .,
 treatment products in Usa , Canada , Mexico , Australia and Brazil Today , Global Research & Data Services is going to publish several market analyses about the markets for water treatment products in some selected countries .,
 According to Finnish L+Ænnen Tehtaat 's CEO Matti Karppinen , now that L+Ænnen Tehtaat has sold the majority of its feed and grain business , it will quickly start to look for acquisitions .,
 `` I am very pleased and proud of our performance last year , '' Chief Executive Juha Rantanen said in a statement .,
 However , the growth margin slowed down due to the financial crisis .,
 Tecnotree 's convergent charging solution includes functionality for prepaid and post-paid billing , charging and rating of voice calls , video calls and raw data traffic for both mobile and fixed networks .,
 `` BasWare 's product sales grew strongly in the financial period , by 24 percent .,
 Secure your files online Like filling out a tax return , making a backup is boring .,
 Frost sold shares for $ 19 million at $ 6.06-7 .12 per share , compared with Friday 's high of $ 11.33 and low of $ 10.14 .,
 The six breweries recorded a 5.2 percent growth in domestic beer sales last year to 270.21 million liters , from 256.88 million liters sold in 2005 .,
 Amer , which bought Salomon from adidas in October , said the job cuts are aimed at boosting competitiveness .,
 The parties have agreed not to disclose the transaction value .,
 Tiimari , the Finnish retailer , reported to have geenrated quarterly revenues totalling EUR 1.3 mn in the 4th quarter 2009 , up from EUR 0.3 mn loss in 2008 .,
 The Process Products orders are for the installation of separation-filtration equipment at three natural gas pipeline projects in China , South America , and Saudi Arabia .,
 KESKO CORPORATION STOCK EXCHANGE RELEASE 28.02.2008 AT 09.30 1 ( 1 ) Kesko Corporation and Aspo plc today signed an agreement by which Aspo acquires the share capital of Kauko-Telko Ltd , a subsidiary wholly owned by Kesko .,
 The tightened competition situation in the production automation market has affected net sales during 2006 , Cencorp said .,
 It is a solid credit that has been compared to a DZ Bank or a Rabobank .,
 Pohjola and cooperative banks have continued to combine their branch office network .,
 Jussi Pesonen , member of the Sampo Board since 2006 , will renounce his seat in Sampo Board .,
 The new activity will incur an investment of about 5 MEUR .,
 Scanfil has also issued a profit warning .,
 in Q1 2010 18 May 2010 - Finnish electrical components maker Salcomp Oy ( HEL : SAL1V ) said today it turned to a net profit of EUR1 .6 m in the first quarter of 2010 versus a loss of EUR2m in the corresponding period last year .,
 Body ES Vostok also owns stakes in power sales companies MosenergosbytBody ( RTS : MSSB ) ( 50.9 % ) , Altaienergosbyt ( 100 % ) , Saratovenergo ( RTS : SARE ) Body ( 48.36 % ) and Tambov Power Sales Company ( RTS : TASB ) ( 49.01 % ) , all ofBodywhich it received from the distribution balance .,
 They can be used to control the speed of electric motors used by industry and municipal engineering , and in power generation using renewable energy .,

In [186]:
help(loaded_model.predict)

Help on method predict in module mlflow.pyfunc:

predict(data: Union[pandas.core.frame.DataFrame, pandas.core.series.Series, numpy.ndarray, ForwardRef('csc_matrix'), ForwardRef('csr_matrix'), List[Any], Dict[str, Any], datetime.datetime, bool, bytes, float, int, str], params: Optional[Dict[str, Any]] = None) -> Union[pandas.core.frame.DataFrame, pandas.core.series.Series, numpy.ndarray, list, str] method of mlflow.pyfunc.PyFuncModel instance
    Generates model predictions.

    If the model contains signature, enforce the input schema first before calling the model
    implementation with the sanitized input. If the pyfunc model does not include model schema,
    the input is passed to the model implementation as is. See `Model Signature Enforcement
    <https://www.mlflow.org/docs/latest/models.html#signature-enforcement>`_ for more details.

    Args:
        data: Model input as one of pandas.DataFrame, numpy.ndarray,
            scipy.sparse.(csc_matrix | csr_matrix), List[Any], or
            Dict[str, numpy.ndarray].
            For model signatures with tensor spec inputs
            (e.g. the Tensorflow core / Keras model), the input data type must be one of
            `numpy.ndarray`, `List[numpy.ndarray]`, `Dict[str, numpy.ndarray]` or
            `pandas.DataFrame`. If data is of `pandas.DataFrame` type and the model
            contains a signature with tensor spec inputs, the corresponding column values
            in the pandas DataFrame will be reshaped to the required shape with 'C' order
            (i.e. read / write the elements using C-like index order), and DataFrame
            column values will be cast as the required tensor spec type. For Pyspark
            DataFrame inputs, MLflow will only enforce the schema on a subset
            of the data rows.
        params: Additional parameters to pass to the model for inference.

            .. Note:: Experimental: This parameter may change or be removed in a future
                release without warning.

    Returns:
        Model predictions as one of pandas.DataFrame, pandas.Series, numpy.ndarray or list.

In [190]:
loaded_model.predict(data = test[["text"]])

                                            predictions
3207  {'positive': 0.21659491956233978, 'negative': ...
1684  {'positive': 0.34155046939849854, 'negative': ...
1044  {'positive': 0.8569769263267517, 'negative': 0...
4145  {'positive': 0.255377858877182, 'negative': 0....
1538  {'positive': 0.24798519909381866, 'negative': ...
...                                                 ...
3691  {'positive': 0.2780744135379791, 'negative': 0...
1507  {'positive': 0.17686673998832703, 'negative': ...
1126  {'positive': 0.16717375814914703, 'negative': ...
180   {'positive': 0.9693070650100708, 'negative': 0...
1215  {'positive': 0.19200772047042847, 'negative': ...

[970 rows x 1 columns]

In [191]:
spacy_model(test_docs[0])

RuntimeError: [E896] There was an error using the static vectors. Ensure that the vectors of the vocab are properly initialized, or set 'include_static_vectors' to False.